version: "3.8"

services:
  hubot:
    build:
      context: ./${PATH_HUBOT}/..
      dockerfile: ./docker/Dockerfile
    image: aegee/hubot:dev
    volumes:
      - "./${PATH_HUBOT}/../scripts:/home/hubot/scripts:ro"
      - "./${PATH_HUBOT}/../utils:/home/hubot/utils:ro"
      - "./${PATH_HUBOT}/../external-scripts.json:/home/hubot/external-scripts.json:ro"
