version: "3.4"

services: 

  hubot:
    image: aegee/hubot:dev
    volumes:
      - "./${PATH_HUBOT}/../scripts:/home/hubot/scripts:ro"
    build:
      context: ./${PATH_HUBOT}/..
      dockerfile: ./docker/Dockerfile
