version: "3.2"

services: 
  redis:
    image: redis

  hubot:
    image: aegee/hubot
    restart: on-failure
    environment: 
      REDIS_URL: redis
      HUBOT_SLACK_TOKEN: ${HUBOT_SLACK_TOKEN}
      EXTRA_PACKAGES: "hubot-auth"
      HUBOT_AUTH_ADMIN: "U42J1D214"
